import { Roboto_Mono } from "next/font/google";
import "@/app/_styles/globals.css";

const roboto = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});
export const metadata = {
  title: "ALi HMT | <FrontEnd/> developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${roboto.variable} tracking-tighter antialiased`}
      >
        <div className="border-orange-600 border-solid box-border border-[16px] h-dvh w-full p-2">
          {children}
        </div>
      </body>
    </html>
  );
}
